/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Hello My-components",
  "description": "welcome to my components",
  "base": "/v1/components/",
  "headTags": [],
  "pages": [
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7b0bf451",
      "path": "/"
    },
    {
      "title": "自适应的轮播",
      "frontmatter": {},
      "regularPath": "/components/my-swiper.html",
      "relativePath": "components/my-swiper.md",
      "key": "v-219c427a",
      "path": "/components/my-swiper.html",
      "headers": [
        {
          "level": 2,
          "title": "自适应的轮播",
          "slug": "自适应的轮播"
        },
        {
          "level": 3,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 3,
          "title": "引入",
          "slug": "引入"
        },
        {
          "level": 3,
          "title": "代码演示",
          "slug": "代码演示"
        },
        {
          "level": 3,
          "title": "属性说明props",
          "slug": "属性说明props"
        },
        {
          "level": 3,
          "title": "事件说明 event",
          "slug": "事件说明-event"
        }
      ]
    },
    {
      "title": "Hello world",
      "frontmatter": {},
      "regularPath": "/api.html",
      "relativePath": "api.md",
      "key": "v-3384772a",
      "path": "/api.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "接口定义",
        "link": "/apiword"
      },
      {
        "text": "接口字段定义",
        "link": "/api"
      },
      {
        "text": "附录：错误码",
        "link": "/error"
      }
    ],
    "sidebar": [
      [
        "/",
        "快速安装"
      ],
      [
        "/api",
        "快速上手"
      ],
      {
        "title": "组件",
        "collapsable": false,
        "sidebarDepth": 0,
        "children": [
          [
            "/components/my-swiper",
            "自适应轮播"
          ]
        ]
      }
    ],
    "displayAllHeaders": true
  }
}